export default function Head() {
  return (
    <>
      <title>Balint Korosi</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <script
        async
        defer
        data-website-id="d4be25cc-53f9-448d-9dfd-f381beba8a0a"
        src="https://umami-anal.vercel.app/umami.js"
      ></script>
      {/* TODO: favicon */}
      {/* <link rel="icon" href="/favicon.ico" /> */}
    </>
  );
}
